import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { fetchKpisApi } from '../../api/overviewApi';
import type { OverviewState, KpiCard } from './overviewTypes';


// createAsyncThunk handles the three states of any async call:
// pending (loading), fulfilled (success), rejected (error).
// The two generics are: <return type, argument type>
// We pass void because fetchKpis takes no arguments.
export const fetchKpis = createAsyncThunk<
  KpiCard[],
  void
>('overview/fetchKpis', async () => {
  return await fetchKpisApi();
});

const initialState: OverviewState = {
  kpis: [],
  status: 'idle',
  error: null,
};

const overviewSlice = createSlice({
  name: 'overview',
  initialState,
  reducers: {},
  // extraReducers handles actions created OUTSIDE this slice —
  // in this case, the three actions auto-generated by createAsyncThunk.
  extraReducers: (builder) => {
    builder
      .addCase(fetchKpis.pending, (state) => {
        state.status = 'loading';
        state.error = null;
      })
      .addCase(fetchKpis.fulfilled, (state, action) => {
        state.status = 'succeeded';
        // action.payload is automatically typed as KpiCard[]
        // because we declared it in createAsyncThunk above.
        state.kpis = action.payload;
      })
      .addCase(fetchKpis.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.error.message ?? 'Failed to fetch KPIs';
      });
  },
});

export default overviewSlice.reducer;